/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "lib_stm32.h"

void GPIO_A()
{
	uint32_t* GPIOA_MODER = (uint32_t*)(PORTA_BASE_ADDR + 0x00);
	*GPIOA_MODER &= ~(0b11 << 5);// return MODER o vi tri so 5 = 0
	*GPIOA_MODER |= 0b01 << 5; // set MODER = OUTPUT  o vi tri so 5
}
void GPIO_B()
{
	GPIO_t* GPIOB = (GPIO_t*)PORTB_BASE_ADDR;
	GPIOB->MODER.MODER5 = INPUT_MODE;
	GPIOB->MODER.MODER5 = OUTPUT_MODE;
}


int main(void)
{
    /* Loop forever */
	while(1)
	{

	}
}
